s1 = str(input('Nhập chuỗi s1 =\n'))
s2 = str(input('Nhập chuỗi s2 =\n'))
s3 = str(input('Nhập chuỗi s3 =\n'))
index = int(input('Nhập index =\n'))
s4 = (s1[index:])
print('Chiều dài chuỗi s1 =', len(s1))
print('Chiều dài chuỗi s2 =', len(s2))
print('Chiều dài chuỗi s3 =', len(s3))
print('Chuỗi s4 =', s4)
print('Chuỗi s2 lặp lại 2 lần =', s2*2)